apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghostfolio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/7K-Hiroba/ghostfolio.git
    targetRevision: HEAD
    path: gitops/argocd/applications
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
